FROM php:8.3-fpm-bullseye

RUN apt-get update
RUN apt-get -y install less
RUN apt-get -y install vim


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

