version: "3.6"

networks:
    symf-network:
        name: symf-network
#        external: true

services:
    symf-app:
        image: symf/symf-app:latest
        container_name: symf-app
        build:
            context: ./
            dockerfile: .docker/app/Dockerfile
        volumes:
            - ./:/var/www/html

        environment:
            BASEDIR: /var/www/html
            HOME: /var/www/html

        networks:
            - symf-network

    symf-web:
        image: symf/symf-web:latest
        container_name: symf-web
        build:
            context: ./
            dockerfile: .docker/web/Dockerfile
        links:
            - symf-app:php_fpm
        ports:
            - "8000:80"
        environment:
            BASEDIR: '/var/www/html'
            PHP_IDE_CONFIG: 'serverName=symf.dv'

        volumes:
            - ./.docker/web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
            - ./shared:/var/shared

        networks:
            - symf-network

