
# nepasigauna ?
services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    Kukulis\PermissionBased\:
        resource: '../src/'

    Kukulis\PermissionBased\Listeners\CheckPermissionRightListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request' }