
# nepasigauna ?
services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


#    Kukulis\PermissionBased\Command\PermissionListCommand:
#        ~

    Kukulis\PermissionBased\:
        resource: '../src/'
